### ISSUE TITLE
GitHub Action for unit tests

### ISSUE THREAD

**Issue by til-schneider** [picturama/picturama#46]
I tried to set up a GitHub Action for unit tests which runs jest. But for some reason, jest runs forever without any output.

If anyone has an idea how to fix this, please let me know.

Here is the last attempt: [.github/workflows/test.yml.disabled](https://github.com/picturama/picturama/blob/master/.github/workflows/test.yml.disabled)

This is what I tried as the last testing step:

```yaml
- run: yarn test
```

```yaml
- run: yarn test --runInBand
```

```yaml
- run: yarn test -u
```

```yaml
- run: yarn test --forceExit
```

```yaml
- run: yarn test --detectOpenHandles --forceExit
```

```yaml
- run: yarn test --ci --detectOpenHandles --forceExit
```

```yaml
- uses: IgnusG/jest-report-action@v2.3.3
  if: always()
  with:
    access-token: ${{ secrets.GITHUB_TOKEN }}
```

```yaml
- uses: mattallty/jest-github-action@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    coverage-comment: false
```
