### ISSUE TITLE
Probably failing to parse big yaml

### ISSUE THREAD

**Issue by FluffyDiscord** [picturama/picturama#89]
Hi, I have pre-generated `picturama.yml` with tags which has 65MB

```yml
photos:
    c5e4a7dd2ac6435e676a7a0fdf94b079.jpg: { tags: [test] }
    # and so on...
```

then added my directory containing images and this chunky yaml file to the folders to scan and clicked "Scan for images" button.
App then freezes and does nothing.
